export const LOCALES = ["uz", "ru", "en"];

export const translations = {
  uz: {
    nav: { strategies: "Strategiyalar", pricing: "Narxlar", login: "Kirish" },
    hero: {
      badge: "7 STRATEGIYA · 6 TIMEFRAME · 1 TOZA SIGNAL",
      titlePre: "Grafikni yuklang. ",
      titleHighlight: "AI qolganini qiladi.",
      desc: "M2 dan H4 gacha — har bir timeframeni AI ko'radi, SMC, FVG, bank manipulatsiyasi va yana 4 ta strategiyani tekshiradi, keyin faqat haqiqatan mos kelganini qoldirib, bitta aniq scalping signali beradi.",
      ctaTry: "Signalni sinab ko'rish",
      ctaPricing: "Narxlarni ko'rish",
    },
    steps: {
      heading: "Uch qadamda signal",
      items: [
        { n: "01", t: "Grafiklarni yuklang", d: "Qaysi timeframelar qo'lingizda bo'lsa (M2, M5, M15, M30, H1, H4) — shularni yuklaysiz. Bittasi ham yetarli." },
        { n: "02", t: "AI barchasini tekshiradi", d: "Yuqori timeframe trend uchun, past timeframe aniq kirish nuqtasi uchun ishlatiladi. 7 strategiya fonda solishtiriladi." },
        { n: "03", t: "Toza signal olasiz", d: "BUY, SELL yoki WAIT. Entry, Stop Loss, Take Profit, R:R va nega bu qaror qabul qilinganining qisqa sababi." },
      ],
    },
    strategiesSection: {
      heading: "Yetti strategiya, bitta miya",
      desc: "AI har birini alohida qidiradi va faqat shu paytda haqiqatan amal qiladiganini signalga qo'shadi — qolganini shovqin deb tashlaydi.",
    },
    cta: {
      heading: "Keyingi savdongizni tasodifga qoldirmang",
      desc: "Bir daqiqada birinchi signalingizni oling.",
      button: "Hoziroq boshlash",
    },
    footer: {
      rights: "Barcha huquqlar himoyalangan.",
      disclaimer: "Bu xizmat moliyaviy maslahat emas — texnik AI tahlili.",
    },
    dashboard: {
      title: "Multi-timeframe scalping tahlili",
      desc: "Har bir timeframe uchun grafik yuklang. AI 7 strategiyani fonda tekshirib, bitta toza signal beradi.",
      roleTrend: "Trend", roleEntry: "Entry", roleConfirm: "Tasdiq",
      entryChart: "ENTRY CHART",
      getSignal: "Signal olish",
      chartsWord: "ta grafik",
      analyzing: "Tahlil qilinmoqda...",
      clear: "Tozalash",
      confidence: "Ishonch",
      entry: "Entry", stopLoss: "Stop Loss", takeProfit: "Take Profit", rr: "R:R",
      showDetails: "Texnik tafsilotlarni ko'rsatish",
      hideDetails: "Texnik tafsilotlarni yashirish",
      noExtra: "AI qo'shimcha strategiya belgisini ahamiyatli deb topmadi.",
      disclaimer: "Bu tahlil AI tomonidan generatsiya qilingan texnik ko'rsatkich bo'lib, moliyaviy maslahat emas.",
      bullish: "Bullish trend", bearish: "Bearish trend", sideways: "Sideways / neytral",
    },
    pricing: {
      back: "Bosh sahifa",
      heading: "Narxlar",
      desc: "Kichikdan boshlang, kerak bo'lganda kattalashtiring.",
      recommended: "Tavsiya etiladi",
      clickNote: "Click orqali to'lov integratsiyasi uchun Click.uz'da merchant (biznes) hisobi ochish kerak — buni ID/INN va tashkilot hujjatlari bilan alohida ariza orqali olasiz. Hozircha bu tugma bosilganda sizga Telegram orqali xabar yuboradigan qilib sozlash mumkin, keyin merchant hisobi tayyor bo'lgach to'liq avtomatlashtiramiz.",
      plans: [
        { name: "Boshlang'ich", price: "Bepul", period: "", features: ["Kuniga 3 ta tahlil", "1 timeframe", "Asosiy signal"], cta: "Bepul boshlash" },
        { name: "Scalper Pro", price: "149 000", period: "so'm / oy", features: ["Cheksiz tahlil", "6 timeframegacha", "Barcha 7 strategiya", "Batafsil texnik tafsilotlar"], cta: "Click orqali to'lash" },
        { name: "Jamoa", price: "Kelishilgan", period: "", features: ["Kanal/guruh uchun ulgurji obuna", "Shaxsiy qo'llab-quvvatlash", "Brend sozlamalari"], cta: "Biz bilan bog'laning" },
      ],
    },
  },

  ru: {
    nav: { strategies: "Стратегии", pricing: "Тарифы", login: "Войти" },
    hero: {
      badge: "7 СТРАТЕГИЙ · 6 ТАЙМФРЕЙМОВ · 1 ЧИСТЫЙ СИГНАЛ",
      titlePre: "Загрузите график. ",
      titleHighlight: "Остальное сделает AI.",
      desc: "От M2 до H4 — AI анализирует каждый таймфрейм, проверяет SMC, FVG, банковскую манипуляцию и ещё 4 стратегии, а затем оставляет только то, что реально совпадает, и выдаёт один чёткий скальпинг-сигнал.",
      ctaTry: "Попробовать сигнал",
      ctaPricing: "Посмотреть тарифы",
    },
    steps: {
      heading: "Сигнал в три шага",
      items: [
        { n: "01", t: "Загрузите графики", d: "Какие таймфреймы есть под рукой (M2, M5, M15, M30, H1, H4) — те и загружайте. Достаточно даже одного." },
        { n: "02", t: "AI проверяет всё", d: "Старший таймфрейм — для тренда, младший — для точной точки входа. 7 стратегий сверяются в фоне." },
        { n: "03", t: "Получаете чистый сигнал", d: "BUY, SELL или WAIT. Entry, Stop Loss, Take Profit, R:R и краткая причина решения." },
      ],
    },
    strategiesSection: {
      heading: "Семь стратегий, один мозг",
      desc: "AI ищет каждую отдельно и добавляет в сигнал только то, что реально работает прямо сейчас — остальное отбрасывает как шум.",
    },
    cta: {
      heading: "Не оставляйте следующую сделку на волю случая",
      desc: "Получите первый сигнал за минуту.",
      button: "Начать сейчас",
    },
    footer: {
      rights: "Все права защищены.",
      disclaimer: "Этот сервис не является финансовой консультацией — только технический AI-анализ.",
    },
    dashboard: {
      title: "Мультитаймфрейм скальпинг-анализ",
      desc: "Загрузите график для каждого таймфрейма. AI проверит 7 стратегий и выдаст один чёткий сигнал.",
      roleTrend: "Тренд", roleEntry: "Вход", roleConfirm: "Подтв.",
      entryChart: "ГРАФИК ВХОДА",
      getSignal: "Получить сигнал",
      chartsWord: "граф.",
      analyzing: "Анализируем...",
      clear: "Очистить",
      confidence: "Уверенность",
      entry: "Entry", stopLoss: "Stop Loss", takeProfit: "Take Profit", rr: "R:R",
      showDetails: "Показать детали",
      hideDetails: "Скрыть детали",
      noExtra: "AI не нашёл дополнительных значимых сигналов стратегий.",
      disclaimer: "Этот анализ сгенерирован AI и является техническим индикатором, а не финансовой консультацией.",
      bullish: "Бычий тренд", bearish: "Медвежий тренд", sideways: "Боковой / нейтральный",
    },
    pricing: {
      back: "Главная",
      heading: "Тарифы",
      desc: "Начните с малого, расширяйтесь по мере необходимости.",
      recommended: "Рекомендуем",
      clickNote: "Для интеграции оплаты через Click нужен мерчант (бизнес) аккаунт на Click.uz — оформляется отдельной заявкой с документами организации. Пока эта кнопка может отправлять заявку через Telegram, а после готовности мерчант-аккаунта всё будет автоматизировано.",
      plans: [
        { name: "Старт", price: "Бесплатно", period: "", features: ["3 анализа в день", "1 таймфрейм", "Базовый сигнал"], cta: "Начать бесплатно" },
        { name: "Scalper Pro", price: "149 000", period: "сум / мес", features: ["Безлимитный анализ", "До 6 таймфреймов", "Все 7 стратегий", "Подробные детали"], cta: "Оплатить через Click" },
        { name: "Команда", price: "По договорённости", period: "", features: ["Групповая подписка для канала", "Персональная поддержка", "Брендинг"], cta: "Связаться с нами" },
      ],
    },
  },

  en: {
    nav: { strategies: "Strategies", pricing: "Pricing", login: "Log in" },
    hero: {
      badge: "7 STRATEGIES · 6 TIMEFRAMES · 1 CLEAN SIGNAL",
      titlePre: "Upload the chart. ",
      titleHighlight: "AI does the rest.",
      desc: "From M2 to H4 — AI reads every timeframe, checks SMC, FVG, bank manipulation and 4 more strategies, then keeps only what actually lines up and hands you one clear scalping signal.",
      ctaTry: "Try a signal",
      ctaPricing: "See pricing",
    },
    steps: {
      heading: "A signal in three steps",
      items: [
        { n: "01", t: "Upload your charts", d: "Whichever timeframes you have (M2, M5, M15, M30, H1, H4) — upload those. Even one is enough." },
        { n: "02", t: "AI checks everything", d: "Higher timeframes set the trend, lower ones pin the exact entry. 7 strategies get cross-checked in the background." },
        { n: "03", t: "Get one clean signal", d: "BUY, SELL, or WAIT. Entry, Stop Loss, Take Profit, R:R, and a short reason for the call." },
      ],
    },
    strategiesSection: {
      heading: "Seven strategies, one brain",
      desc: "AI checks each one on its own and only keeps what's genuinely relevant right now — everything else gets dropped as noise.",
    },
    cta: {
      heading: "Don't leave your next trade to chance",
      desc: "Get your first signal in under a minute.",
      button: "Start now",
    },
    footer: {
      rights: "All rights reserved.",
      disclaimer: "This service is not financial advice — technical AI analysis only.",
    },
    dashboard: {
      title: "Multi-timeframe scalping analysis",
      desc: "Upload a chart for each timeframe. AI checks 7 strategies in the background and returns one clean signal.",
      roleTrend: "Trend", roleEntry: "Entry", roleConfirm: "Confirm",
      entryChart: "ENTRY CHART",
      getSignal: "Get signal",
      chartsWord: "chart(s)",
      analyzing: "Analyzing...",
      clear: "Clear",
      confidence: "Confidence",
      entry: "Entry", stopLoss: "Stop Loss", takeProfit: "Take Profit", rr: "R:R",
      showDetails: "Show technical details",
      hideDetails: "Hide technical details",
      noExtra: "AI didn't find any extra strategy signals worth flagging.",
      disclaimer: "This analysis is AI-generated technical output, not financial advice.",
      bullish: "Bullish trend", bearish: "Bearish trend", sideways: "Sideways / neutral",
    },
    pricing: {
      back: "Home",
      heading: "Pricing",
      desc: "Start small, scale up when you need to.",
      recommended: "Recommended",
      clickNote: "Click payment integration requires a Click.uz merchant (business) account, which is set up separately with organization documents. For now this button can notify you via Telegram, and once the merchant account is ready we'll fully automate it.",
      plans: [
        { name: "Starter", price: "Free", period: "", features: ["3 analyses / day", "1 timeframe", "Basic signal"], cta: "Start free" },
        { name: "Scalper Pro", price: "149,000", period: "UZS / mo", features: ["Unlimited analyses", "Up to 6 timeframes", "All 7 strategies", "Detailed technical breakdown"], cta: "Pay with Click" },
        { name: "Team", price: "Custom", period: "", features: ["Bulk subscription for a channel/group", "Dedicated support", "Branding options"], cta: "Contact us" },
      ],
    },
  },
};
